//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApplication {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyWebApplication.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string amd_oc {
            get {
                return ResourceManager.GetString("amd_oc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string autofan {
            get {
                return ResourceManager.GetString("autofan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HIVE_HOST_URL=&quot;_HIVE_HOST_URL_&quot;
        ///RIG_ID=_RIG_ID_
        ///RIG_PASSWD=&quot;_RIG_PASSWD_&quot;
        ///WD_ENABLED=0
        ///X_DISABLED=0
        ///WORKER_NAME=&quot;_WORKER_NAME_&quot;
        ///MINER=custom
        ///TIMEZONE=&quot;Asia/Shanghai&quot; 的本地化字符串。
        /// </summary>
        public static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #### nvidia-oc.conf
        ///CLOCK=&quot;1100&quot;
        ///MEM=&quot;1400&quot;
        ///FAN=&quot;&quot;
        ///PLIMIT=&quot;&quot;
        ///LOGO_BRIGHTNESS=0
        ///OHGODAPILL_ENABLED=
        ///OHGODAPILL_START_TIMEOUT=
        ///OHGODAPILL_ARGS=&quot;&quot;
        ///RUNNING_DELAY= 的本地化字符串。
        /// </summary>
        public static string nvidia_oc {
            get {
                return ResourceManager.GetString("nvidia_oc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #### wallet.conf
        ///CUSTOM_MINER=&quot;gminer_2.83&quot;
        ///CUSTOM_INSTALL_URL=&quot;https://code.aliyun.com/easyos/ezminer3/raw/master/gminer/gminer_2.83.tar.gz&quot;
        ///CUSTOM_ALGO=&quot;eth&quot;
        ///CUSTOM_TEMPLATE=&quot;0x6004A7d9Bc4D10f87822991b7D1747f40E1806bC&quot;
        ///CUSTOM_WORKER=&quot;HS3080&quot;
        ///CUSTOM_URL=&quot;stratum+ssl://47.243.40.156:6667&quot;
        ///CUSTOM_PASS=&quot;&quot;
        ///CUSTOM_USER_CONFIG=&apos;&apos;
        ///META=&apos;{&quot;custom&quot;:{&quot;coin&quot;:&quot;eth&quot;}}&apos; 的本地化字符串。
        /// </summary>
        public static string wallet {
            get {
                return ResourceManager.GetString("wallet", resourceCulture);
            }
        }
    }
}
