//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 设置挖矿模板 的本地化字符串。
        /// </summary>
        public static string AddWKTemplatePageTitle {
            get {
                return ResourceManager.GetString("AddWKTemplatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 foxikg.com 的本地化字符串。
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blank 的本地化字符串。
        /// </summary>
        public static string BlankPageTitle {
            get {
                return ResourceManager.GetString("BlankPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据格 的本地化字符串。
        /// </summary>
        public static string DataGridPageTitle {
            get {
                return ResourceManager.GetString("DataGridPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 矿机列表 的本地化字符串。
        /// </summary>
        public static string KJManagePageTitle {
            get {
                return ResourceManager.GetString("KJManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页 的本地化字符串。
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 钱包模板列表 的本地化字符串。
        /// </summary>
        public static string QBListPageTitle {
            get {
                return ResourceManager.GetString("QBListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings page placeholder text.  Your app description goes here. 的本地化字符串。
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About this application 的本地化字符串。
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose Theme 的本地化字符串。
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Personalization 的本地化字符串。
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Privacy Statement 的本地化字符串。
        /// </summary>
        public static string SettingsPagePrivacyStatementText {
            get {
                return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加超频模板 的本地化字符串。
        /// </summary>
        public static string ShellAddCPTemplatePage {
            get {
                return ResourceManager.GetString("ShellAddCPTemplatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加挖矿模板 的本地化字符串。
        /// </summary>
        public static string ShellAddWKTemplatePage {
            get {
                return ResourceManager.GetString("ShellAddWKTemplatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blank 的本地化字符串。
        /// </summary>
        public static string ShellBlankPage {
            get {
                return ResourceManager.GetString("ShellBlankPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超频模板 的本地化字符串。
        /// </summary>
        public static string ShellCPTemplatePage {
            get {
                return ResourceManager.GetString("ShellCPTemplatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataGrid 的本地化字符串。
        /// </summary>
        public static string ShellDataGridPage {
            get {
                return ResourceManager.GetString("ShellDataGridPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后退 的本地化字符串。
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open or close navigation 的本地化字符串。
        /// </summary>
        public static string ShellHamburgerButtonName {
            get {
                return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 矿机管理 的本地化字符串。
        /// </summary>
        public static string ShellKJManagePage {
            get {
                return ResourceManager.GetString("ShellKJManagePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页 的本地化字符串。
        /// </summary>
        public static string ShellMainPage {
            get {
                return ResourceManager.GetString("ShellMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 钱包模板列表 的本地化字符串。
        /// </summary>
        public static string ShellQBListPage {
            get {
                return ResourceManager.GetString("ShellQBListPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string ShellSettingsPage {
            get {
                return ResourceManager.GetString("ShellSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 挖矿模板 的本地化字符串。
        /// </summary>
        public static string ShellWKTemplatePage {
            get {
                return ResourceManager.GetString("ShellWKTemplatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增钱包模板页 的本地化字符串。
        /// </summary>
        public static string Shell新增钱包模板页Page {
            get {
                return ResourceManager.GetString("Shell新增钱包模板页Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 矿机详细信息 的本地化字符串。
        /// </summary>
        public static string Shell矿机详细信息Page {
            get {
                return ResourceManager.GetString("Shell矿机详细信息Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 挖矿模板列表 的本地化字符串。
        /// </summary>
        public static string WKTemplatePageTitle {
            get {
                return ResourceManager.GetString("WKTemplatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加超频模板 的本地化字符串。
        /// </summary>
        public static string 新增超频模板页_标题 {
            get {
                return ResourceManager.GetString("新增超频模板页_标题", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增钱包模板页 的本地化字符串。
        /// </summary>
        public static string 新增钱包模板页_标题 {
            get {
                return ResourceManager.GetString("新增钱包模板页_标题", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://192.168.1.2 的本地化字符串。
        /// </summary>
        public static string 服务器地址 {
            get {
                return ResourceManager.GetString("服务器地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 矿机详细信息 的本地化字符串。
        /// </summary>
        public static string 矿机详细信息PageTitle {
            get {
                return ResourceManager.GetString("矿机详细信息PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超频模板 的本地化字符串。
        /// </summary>
        public static string 超频模板列表页_标题 {
            get {
                return ResourceManager.GetString("超频模板列表页_标题", resourceCulture);
            }
        }
    }
}
